### ISSUE TITLE
siteHandle not found

### ISSUE THREAD

**Issue by TimmermansL** [statikbe/craft3-translate#11]
TypeError craft\services\sites::getsitebyhandle(): argument #1 ($sitehandle) must be of type string, null given

For single language site

Translate v2.1.1
php v8.0
Craft v4.4.6.1

Adding "null" at line 44 in craft-translate > templates can solve this:
`{% set selectedSite = craft.app.request.getQueryParam('site', null)  ? craft.app.sites.getSiteByHandle(craft.app.request.getQueryParam('site')) : craft.app.sites.primarySite %}`

**Comment by janhenckens** [comment]
Fixed & released in 2.1.2
